import { cleanupOutdatedCaches, precacheAndRoute } from 'workbox-precaching';

// A new build's worker activates at once and takes over the open pages, instead of waiting until
// every page of the site is closed, so the next page load gets the new build. Pages already open
// switch to it at a safe moment (lib/serviceWorkerUpdate.js). clients.claim() directly, as
// workbox-core's clientsClaim() does: workbox-core is not a direct dependency of the client.
self.skipWaiting();
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Deletes precaches left by older Workbox versions. This build's own outdated entries are
// removed by precacheAndRoute when this worker activates.
cleanupOutdatedCaches();

// Precaches all of the assets generated by your build process
precacheAndRoute(self.__WB_MANIFEST || []);

self.addEventListener('push', (event) => {
  if (event.data) {
    const data = event.data.json();
    
    const options = {
      body: data.body,
      icon: data.icon || '/pwa-192x192.png',
      badge: '/pwa-192x192.png',
      vibrate: [200, 100, 200, 100, 200],
      data: data.data || { url: '/' },
      requireInteraction: true
    };

    event.waitUntil(
      self.registration.showNotification(data.title || 'New Notification', options)
    );
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  
  if (event.notification.data && event.notification.data.url) {
    event.waitUntil(
      clients.openWindow(event.notification.data.url)
    );
  } else {
    event.waitUntil(
      clients.openWindow('/')
    );
  }
});
